CREATE TABLE IF NOT EXISTS users
(
    id                      BIGINT                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name              VARCHAR(80)              NOT NULL,
    last_name               VARCHAR(80)              NOT NULL,
    birthday_at             DATE                     NOT NULL,
    email                   VARCHAR(80)              NOT NULL,
    password                VARCHAR(100)             NOT NULL,
    role                    VARCHAR(20)              NOT NULL,
    CONSTRAINT email_unique UNIQUE (email)
);

CREATE INDEX index_users_email
    ON users (email);

CREATE INDEX index_users_id
    ON users (id);